title = "Notre-Dame de Paris"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

background_color_class = "bg-gray"

[languages]
  [languages.en]
    title = "Gabriella Roos"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  site_logo = "logo.png"
  description = "Video Editor"
  facebook = "https://www.facebook.com/gabriellaroosfilm/"
  instagram = "https://www.instagram.com/gabyroos_film/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
